<?php

namespace Jp\YahooApis\YDN\V201903\AdGroupTarget;

class TargetType
{
    const __default = 'AD_SCHEDULE_TARGET';
    const AD_SCHEDULE_TARGET = 'AD_SCHEDULE_TARGET';
    const GEO_TARGET = 'GEO_TARGET';
    const AGE_TARGET = 'AGE_TARGET';
    const GENDER_TARGET = 'GENDER_TARGET';
    const INTEREST_CATEGORY = 'INTEREST_CATEGORY';
    const SITE_CATEGORY = 'SITE_CATEGORY';
    const SITE_RETARGETING = 'SITE_RETARGETING';
    const SEARCH_TARGET = 'SEARCH_TARGET';
    const PLACEMENT_TARGET = 'PLACEMENT_TARGET';
    const DEVICE_TARGET = 'DEVICE_TARGET';
    const CARRIER_TARGET = 'CARRIER_TARGET';
    const APP_TARGET = 'APP_TARGET';
    const OS_TARGET = 'OS_TARGET';
    const OS_VERSION_TARGET = 'OS_VERSION_TARGET';


}
