<?php

namespace Jp\YahooApis\YDN\V201903\ConversionTracker;

class StatsPeriod
{
    const __default = 'DEFINITE_VALUE_YESTERDAY';
    const DEFINITE_VALUE_YESTERDAY = 'DEFINITE_VALUE_YESTERDAY';
    const DEFINITE_VALUE_LASTBSDAY = 'DEFINITE_VALUE_LASTBSDAY';
    const DEFINITE_VALUE_LASTWEEK = 'DEFINITE_VALUE_LASTWEEK';
    const DEFINITE_VALUE_WEEK = 'DEFINITE_VALUE_WEEK';
    const DEFINITE_VALUE_TWOWEEK = 'DEFINITE_VALUE_TWOWEEK';
    const DEFINITE_VALUE_THIRTYDAY = 'DEFINITE_VALUE_THIRTYDAY';
    const DEFINITE_VALUE_LASTMONTH = 'DEFINITE_VALUE_LASTMONTH';
    const REALTIME_TODAY = 'REALTIME_TODAY';
    const REALTIME_MONTH = 'REALTIME_MONTH';
    const DEFINITE_VALUE_LAST13MONTH = 'DEFINITE_VALUE_LAST13MONTH';
    const CUSTOM_DATE = 'CUSTOM_DATE';


}
